services:
    server:
        env_file:
            - .env
        image: mc-server-modded
        build:
            context: .
        ports:
            - "25565:25565"
            - "127.0.0.1:25575:25575"
        volumes:
            - "${HOST_SERVER_PATH}:/mc-server"
